FROM ghcr.io/cyber-dojo-languages/gplusplus:4a36012
LABEL maintainer=estermann.michel@gmail.com

COPY googletest-release-1.17.0.zip /usr/src
COPY install.sh .
RUN ./install.sh && rm ./install.sh
COPY red_amber_green.rb /usr/local/bin
